// action types for businesses
export const FETCH_BUSINESSES_START = 'FETCH_BUSINESSES_START';
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';
export const FETCH_BUSINESSES_FAIL = 'FETCH_BUSINESSES_FAIL';

// finding user location
export const FETCH_USER_LOCATION_SUCCESS = 'FETCH_USER_LOCATION_SUCCESS';
export const FETCH_USER_LOCATION_FAIL = 'FETCH_USER_LOCATION_FAIL';