// action types for businesses
export const FETCH_BUSINESSES_START = 'FETCH_BUSINESSES_START';
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';
export const FETCH_BUSINESSES_FAIL = 'FETCH_BUSINESSES_FAIL';

// finding user location
export const FETCH_USER_LOCATION_SUCCESS = 'FETCH_USER_LOCATION_SUCCESS';
export const FETCH_USER_LOCATION_FAIL = 'FETCH_USER_LOCATION_FAIL';

// category page
export const CATEGORY_NAME = 'CATEGORY_NAME';
export const FETCH_BUSINESSES_IN_CATEGORY_START = 'FETCH_BUSINESSES_IN_CATEGORY_START';
export const FETCH_BUSINESSES_IN_CATEGORY_SUCCESS = 'FETCH_BUSINESSES_IN_CATEGORY_SUCCESS';
export const FETCH_BUSINESSES_IN_CATEGORY_FAIL = 'FETCH_BUSINESSES_IN_CATEGORY_FAIL';

// business detail page
export const BUSINESS_DETAIL_SLUG = 'BUSINESS_DETAIL_SLUG';

// products
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

// product detail page
export const PRODUCT_DETAIL_SLUG = 'PRODUCT_DETAIL_SLUG';
